<?php
session_start();
include("connect.php");

// Only allow admin
if (!isset($_SESSION['role']) || $_SESSION['role'] !== 'admin') {
    header("Location: homePage.php");
    exit();
}

// Fetch counts
$totalUsers = $conn->query("SELECT COUNT(*) FROM user")->fetch_row()[0] ?? 0;
$totalNotes = $conn->query("SELECT COUNT(*) FROM notes")->fetch_row()[0] ?? 0;
$totalDownloads = $conn->query("SELECT COUNT(*) FROM note_downloads")->fetch_row()[0] ?? 0;
$totalReports = $conn->query("SELECT COUNT(*) FROM report_note")->fetch_row()[0] ?? 0;

// Auto download TXT report
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['download_report'])) {
    header('Content-Type: text/plain');
    header('Content-Disposition: attachment; filename="StudyHive_Report.txt"');

    echo "📊 StudyHive System Report\n";
    echo "Generated On: " . date("Y-m-d H:i:s") . "\n";
    echo "Generated By: " . $_SESSION['user_Name'] . "\n\n";

    echo "===== System Overview =====\n";
    echo "👤 Total Users      : $totalUsers\n";
    echo "📄 Total Notes      : $totalNotes\n";
    echo "⬇️  Total Downloads  : $totalDownloads\n";
    echo "🚩 Total Reports    : $totalReports\n\n";

    echo "===== Description =====\n";
    echo "- Users     = Registered accounts.\n";
    echo "- Notes     = Uploads by all users.\n";
    echo "- Downloads = Total download activity.\n";
    echo "- Reports   = User-submitted content issues.\n";

    echo "\n📌 Keep monitoring weekly for system health.\n";
    exit();
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Admin Dashboard - StudyHive</title>
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f3f4f6;
      margin: 0;
    }

    .header {
      background-color: #ec97ec;
      color: #5e1b5e;
      text-align: center;
      padding: 30px 20px;
      font-family: Cambria, Cochin, Georgia, Times, "Times New Roman", serif;
      box-shadow: 0 4px 10px rgba(0,0,0,0.1);
    }

    .header h1 {
      margin: 0;
      font-size: 2.8em;
      font-weight: bold;
    }

    .header p {
      font-size: 1.2em;
      margin-top: 10px;
      color: #3d0d3d;
    }

    .navbar {
      background-color: #660066;
      position: sticky;
      top: 0;
      display: flex;
      align-items: center;
      justify-content: center;
      padding: 0 10px;
      height: 60px;
      box-shadow: 0 2px 5px rgba(0,0,0,0.5);
    }

    .navbar .logo {
      height: 60px;
    }

    .navbar ul {
      list-style: none;
      display: flex;
      margin: 0;
      padding: 0;
    }

    .navbar li {
      margin-left: 10px;
    }

  .navbar a {
  position: relative;
  text-decoration: none;
  color: white;
  padding: 14px 16px;
  display: block;
  font-size: 14px;
  font-weight: bold;
  text-transform: uppercase;
  transition: color 0.3s ease;
}

.navbar a::after {
  content: "";
  position: absolute;
  bottom: 6px; /* space below text */
  left: 50%;
  transform: translateX(-50%) scaleX(0);
  transform-origin: center;
  width: 60%;  /* underline is 60% of the word width */
  height: 3px;
  background-color: white;
  transition: transform 0.3s ease;
}

.navbar a:hover::after,
.navbar a.active::after {
  transform: translateX(-50%) scaleX(1);
}

    .navbar a:hover {
      transform: scale(1.09);
    }

    .container {
      max-width: 1000px;
      margin: 40px auto;
      background-color: #660066;
      color: white;
      border-radius: 20px;
      padding: 40px;
      box-shadow: 0 4px 20px rgba(0,0,0,0.15);
    }

      .card-container {
      display: flex;
      justify-content: space-around;
      flex-wrap: wrap;
      gap: 30px;
      margin-top: 30px;
    }

    .card {
      background-color: #f7d7f7;
      border-radius: 15px;
      padding: 25px 35px;
      width: 200px;
      text-align: center;
      box-shadow: 0 3px 10px rgba(102, 0, 102, 0.3);
      transition: transform 0.3s ease;
    }

    .card-link {
      text-decoration: none;
      color: inherit;
    }

    .card:hover {
      transform: scale(1.05);
    }

    .card h2 {
      margin: 0 0 10px 0;
      font-size: 3em;
      color: #660066;
    }

    .card p {
      margin: 0;
      font-size: 18px;
      font-weight: bold;
      color: #3d0d3d;
    }

    .chart-container {
      margin-top: 50px;
      background: white;
      padding: 20px;
      border-radius: 10px;
      display: flex;
      flex-direction: column;
      align-items: center;
    }

    canvas {
      background: #fff;
      border: 1px solid #ddd;
      border-radius: 10px;
      margin: 20px auto;
    }

    .button-row {
      display: flex;
      justify-content: center;
      gap: 20px;
      margin-top: 30px;
      flex-wrap: wrap;
    }

    .report-btn {
      padding: 12px 24px;
      background-color: #f7d7f7;
      color: #660066;
      font-size: 16px;
      font-weight: bold;
      border: none;
      border-radius: 8px;
      cursor: pointer;
      transition: background-color 0.3s ease;
      text-decoration: none;
    }

    .report-btn:hover {
      background-color: #f0bdf0;
    }
  </style>
</head>
<body>

<header class="header">
  <img src="images/whiteLogo.png" alt="Logo" style="width: 180px; height: auto;">
  <h1>Admin Dashboard</h1>
  <p>Welcome, <?= htmlspecialchars($_SESSION['user_Name']) ?>!</p>
</header>

<nav class="navbar">
  <ul>
    <li><a href="adminDashboard.php" class="active">Dashboard</a></li>
    <li><a href="adminUsers.php">Manage Users</a></li>
    <li><a href="adminNotes.php">Manage Notes</a></li>
    <li><a href="adminReports.php">Reported Content</a></li>
    <li><a href="adminFeedback.php">Feedback</a></li>
    <li><a href="logout.php">Log out</a></li>
  </ul>
</nav>

<main class="container">
  <h1 style="text-align:center;">System Overview</h1>

  <div class="card-container">
    <a href="adminUsers.php" class="card-link"><div class="card"><h2><?= $totalUsers ?></h2><p>Total Users</p></div></a>
    <a href="adminNotes.php" class="card-link"><div class="card"><h2><?= $totalNotes ?></h2><p>Total Notes</p></div></a>
    <a href="adminAnalytics.php" class="card-link"><div class="card"><h2><?= $totalDownloads ?></h2><p>Total Downloads</p></div></a>
    <a href="adminReports.php" class="card-link"><div class="card"><h2><?= $totalReports ?></h2><p>Reported Notes</p></div></a>
  </div>

  <div class="chart-container">
    <h2 style="color: #660066;">System Stats Chart</h2>
    <canvas id="statsChart" width="600" height="400"></canvas>

    <div class="button-row">
      <form method="POST">
        <button type="submit" name="download_report" class="report-btn">📄 Download Report Summary</button>
      </form>

      <button class="report-btn" onclick="downloadChart()">📊 Download Report & Graph</button>
    </div>
  </div>
</main>

<script>
const ctx = document.getElementById('statsChart').getContext('2d');
const chart = new Chart(ctx, {
  type: 'bar',
  data: {
    labels: ['Users', 'Notes', 'Downloads', 'Reports'],
    datasets: [{
      label: 'Total Count',
      data: [<?= $totalUsers ?>, <?= $totalNotes ?>, <?= $totalDownloads ?>, <?= $totalReports ?>],
      backgroundColor: ['#cc33cc', '#993399', '#ff99cc', '#ff6666']
    }]
  },
  options: {
    responsive: false,
    plugins: { legend: { display: false } },
    scales: { y: { beginAtZero: true } }
  }
});

function downloadChart() {
  const link = document.createElement('a');
  link.download = 'system_graph.png';
  link.href = chart.toBase64Image();
  link.click();
}
</script>

<?php include('footer.php'); ?>
</body>
</html>
